version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"
        ]
      interval: 5s
      timeout: 30s
      retries: 10
      start_period: 20s
  web:
    build: .
    command: # To run without development server, comment these lines
      flask --app app run --host 0.0.0.0 --port 8000 --debug
    volumes:
      - .:/app/
    ports:
      - "8000:8000"
    environment:
      - QUIZODYSSEY_DATABASE_URI=postgresql://postgres:postgres@db/postgres
      - QUIZODYSSEY_SECRET_KEY=${QUIZODYSSEY_SECRET_KEY}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
